name: build_and_push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          ### !!! Note !!! rather than doing this right, I'm just going to
          ### Manually set these variables when changing the base
          tags: shavera/cmake-base:latest, shavera/cmake-base:24.04
